### ISSUE TITLE
Maximum call stack size exceeded on ui5 serve and ui5 build

### ISSUE THREAD

**Issue by abf-martinc** [SAP-samples/ui5-typescript-walkthrough#11] opened 2024-04-28 11:29 UTC
Hello,

I was trying your tutorial on ui5 typescript. 
https://openui5.hana.ondemand.com/topic/be33d0120da1491baa490fc01eaaf018

Although without changing your source i was not able to run the code.
Either with the commands _"ui5 serve"_ nor _"ui5 build"._ It will always stop with an **error: "Maximum call stack size exceeded"**

I even tried to set up fresh in a VM with Linux MINT, as I thought it might be an installation issue. But I get the same problems there.
Also I cannot run ui5 build on your last step of the Walkthrough with (just) JavaScript. Same Error.
https://openui5.hana.ondemand.com/topic/ae1be8cc26064274bbc5925a9cd59640

_"ui5 serve"_ works when i remove "ui5-middleware-serveframework": "^3.0.0" from the installation and ui5.yaml middleware.
_"ui5 build"_ won't work event with this..

I am using the latest version of node 22.0.0 and npm 10.6.0.

**Here is the output on the terminal:**

npm run build

> ui5.walkthrough.step38@1.0.0 build
> ui5 build --all --clean-dest

info graph:helpers:ui5Framework Using OpenUI5 version: 1.120.1
info ProjectBuilder Preparing build for project ui5.walkthrough
info ProjectBuilder   Target directory: ./dist
info ProjectBuilder   Including all dependencies
info ProjectBuilder Processing 6 projects
info ProjectBuilder Cleaning target directory...
info Project 1 of 6: ❯ Building library project sap.ui.core...
info sap.ui.core › Running task escapeNonAsciiCharacters...

⚠️  Process Failed With Error

Error Message:
Maximum call stack size exceeded

For details, execute the same command again with an additional '--verbose' parameter
(The --verbose parameter won't change anything in the output)

**We really need to switch to a newer UI5 version, prefered with TypeScript!!**

**Please help!**

**Comment by petermuessig** [comment] 2024-04-29 15:07
@matz3 @RandomByte @flovogt  - there's a problem with the UI5 build and Node version 22. When switching to Node version 22 and running `npm run build` which finally calls `ui5 build` then this causes the `Maximum call stack size exceeded issue`. Can one of you please take a look? The issues happens already in the first executed task `escapeNonAsciiCharacters`.

**Comment by matz3** [comment] 2024-04-29 15:36
This looks like a [Node.js regression](https://github.com/nodejs/node/issues/52705) that has been fixed yesterday via https://github.com/nodejs/node/pull/52708.

@abf-martinc please consider using a LTS version of Node.js for productive usage.

**Comment by petermuessig** [comment] 2024-04-30 13:55
In this case, I think we can close the issue here. Thanks @matz3

**Closed by petermuessig** 2024-04-30 13:55 UTC
